import type {
  Account,
  AppNotification,
  BankCard,
  Beneficiary,
  Biller,
  Branch,
  Merchant,
  SpendingCategory,
  Transaction,
} from './types'

/**
 * Every value in this module is fabricated for UI demonstration. There is no
 * backend: screens read from these arrays and mutate only client-side state.
 */

export const CUSTOMER = {
  name: 'Ayesha Siddiqui',
  initials: 'AS',
  email: 'ayesha.siddiqui@example.com',
  phone: '+92 300 1234567',
  cnic: '42101-•••••••-8',
  memberSince: '2014',
  city: 'Karachi',
  tier: 'Priority Banking',
}

export const accounts: Account[] = [
  {
    id: 'acc-current',
    nickname: 'Everyday Current',
    productName: 'Zenith Current Account',
    kind: 'current',
    maskedNumber: '•••• 4821',
    iban: 'PK36ZNTH0000001123456702',
    branch: 'Clifton Branch, Karachi',
    currency: 'PKR',
    balance: 2_468_042,
    availableBalance: 2_431_540,
    changePercent: 8.4,
    monthlyIncome: 684_000,
    monthlySpend: 216_040,
  },
  {
    id: 'acc-savings',
    nickname: 'Rainy Day Savings',
    productName: 'Zenith Savings Account',
    kind: 'savings',
    maskedNumber: '•••• 7130',
    iban: 'PK36ZNTH0000001198765401',
    branch: 'Clifton Branch, Karachi',
    currency: 'PKR',
    balance: 1_186_500,
    availableBalance: 1_186_500,
    changePercent: 2.1,
    monthlyIncome: 12_400,
    monthlySpend: 0,
  },
  {
    id: 'acc-deposit',
    nickname: 'Term Deposit',
    productName: 'Zenith Term Deposit',
    kind: 'deposit',
    maskedNumber: '•••• 9052',
    iban: 'PK36ZNTH0000001155221109',
    branch: 'Gulberg Branch, Lahore',
    currency: 'PKR',
    balance: 5_000_000,
    availableBalance: 0,
    changePercent: 0,
    monthlyIncome: 47_500,
    monthlySpend: 0,
  },
]

/** Fixed clock so the demo reads identically on every run. */
export const TODAY = new Date('2024-03-21T11:20:00')

function daysAgo(days: number, hours: number, minutes = 0): string {
  const date = new Date(TODAY)
  date.setDate(date.getDate() - days)
  date.setHours(hours, minutes, 0, 0)
  return date.toISOString()
}

export const transactions: Transaction[] = [
  {
    id: 'imtiaz-superstore',
    accountId: 'acc-current',
    merchant: 'Imtiaz Super Market',
    category: 'Groceries',
    date: daysAgo(0, 10, 42),
    amount: 8_624,
    direction: 'debit',
    initials: 'IM',
    tone: 'green',
    reference: 'TRX-20240321-0042',
  },
  {
    id: 'salary-credit',
    accountId: 'acc-current',
    merchant: 'Habib Textiles Payroll',
    category: 'Salary',
    date: daysAgo(1, 9, 0),
    amount: 428_000,
    direction: 'credit',
    initials: 'HT',
    tone: 'brand',
    reference: 'TRX-20240320-0011',
  },
  {
    id: 'k-electric',
    accountId: 'acc-current',
    merchant: 'K-Electric',
    category: 'Utilities',
    date: daysAgo(2, 14, 15),
    amount: 18_450,
    direction: 'debit',
    initials: 'KE',
    tone: 'cyan',
    reference: 'TRX-20240319-0208',
  },
  {
    id: 'careem-ride',
    accountId: 'acc-current',
    merchant: 'Careem',
    category: 'Transport',
    date: daysAgo(3, 8, 5),
    amount: 1_240,
    direction: 'debit',
    initials: 'CA',
    tone: 'violet',
    reference: 'TRX-20240318-0155',
  },
  {
    id: 'kolachi-dining',
    accountId: 'acc-current',
    merchant: 'Kolachi Restaurant',
    category: 'Dining',
    date: daysAgo(4, 21, 30),
    amount: 12_800,
    direction: 'debit',
    initials: 'KR',
    tone: 'sky',
    reference: 'TRX-20240317-0311',
  },
  {
    id: 'jazz-topup',
    accountId: 'acc-current',
    merchant: 'Jazz Prepaid Top-up',
    category: 'Mobile',
    date: daysAgo(5, 18, 12),
    amount: 1_500,
    direction: 'debit',
    initials: 'JZ',
    tone: 'cyan',
    reference: 'TRX-20240316-0092',
  },
  {
    id: 'ibft-in-hassan',
    accountId: 'acc-current',
    merchant: 'Hassan Raza',
    category: 'Transfer',
    date: daysAgo(6, 12, 44),
    amount: 35_000,
    direction: 'credit',
    initials: 'HR',
    tone: 'green',
    reference: 'TRX-20240315-0501',
  },
  {
    id: 'khaadi-shopping',
    accountId: 'acc-current',
    merchant: 'Khaadi',
    category: 'Shopping',
    date: daysAgo(7, 16, 25),
    amount: 24_990,
    direction: 'debit',
    initials: 'KH',
    tone: 'violet',
    reference: 'TRX-20240314-0177',
  },
  {
    id: 'ssgc-gas',
    accountId: 'acc-current',
    merchant: 'Sui Southern Gas',
    category: 'Utilities',
    date: daysAgo(9, 11, 5),
    amount: 6_320,
    direction: 'debit',
    initials: 'SS',
    tone: 'cyan',
    reference: 'TRX-20240312-0064',
  },
  {
    id: 'rent-housing',
    accountId: 'acc-current',
    merchant: 'Apartment Rent',
    category: 'Housing',
    date: daysAgo(11, 9, 30),
    amount: 98_000,
    direction: 'debit',
    initials: 'AR',
    tone: 'brand',
    reference: 'TRX-20240310-0002',
  },
  {
    id: 'profit-savings',
    accountId: 'acc-savings',
    merchant: 'Monthly Profit Credit',
    category: 'Salary',
    date: daysAgo(10, 8, 0),
    amount: 12_400,
    direction: 'credit',
    initials: 'AH',
    tone: 'green',
    reference: 'TRX-20240311-0900',
  },
  {
    id: 'savings-transfer',
    accountId: 'acc-savings',
    merchant: 'Transfer to Current',
    category: 'Transfer',
    date: daysAgo(13, 15, 20),
    amount: 50_000,
    direction: 'debit',
    initials: 'TC',
    tone: 'sky',
    reference: 'TRX-20240308-0410',
  },
  {
    id: 'deposit-profit',
    accountId: 'acc-deposit',
    merchant: 'Mahana Munafa Payout',
    category: 'Salary',
    date: daysAgo(8, 10, 0),
    amount: 47_500,
    direction: 'credit',
    initials: 'MM',
    tone: 'green',
    reference: 'TRX-20240313-0700',
  },
]

export const beneficiaries: Beneficiary[] = [
  {
    id: 'fatima-noor',
    name: 'Fatima Noor',
    initials: 'FN',
    tone: 'lavender',
    bank: 'Meezan Bank',
    maskedNumber: '•••• 2091',
    iban: 'PK24MEZN0001234567892091',
    transferLimit: 500_000,
    raastEnabled: true,
    favourite: true,
  },
  {
    id: 'usman-tariq',
    name: 'Usman Tariq',
    initials: 'UT',
    tone: 'peach',
    bank: 'HBL',
    maskedNumber: '•••• 7712',
    iban: 'PK11HABB0009876543217712',
    transferLimit: 250_000,
    raastEnabled: true,
    favourite: true,
  },
  {
    id: 'zainab-ali',
    name: 'Zainab Ali',
    initials: 'ZA',
    tone: 'mint',
    bank: 'Zenith Bank',
    maskedNumber: '•••• 3480',
    iban: 'PK36ZNTH0000004455663480',
    transferLimit: 1_000_000,
    raastEnabled: true,
    favourite: true,
  },
  {
    id: 'bilal-ahmed',
    name: 'Bilal Ahmed',
    initials: 'BA',
    tone: 'sky',
    bank: 'UBL',
    maskedNumber: '•••• 6155',
    iban: 'PK77UNIL0003344556616155',
    transferLimit: 200_000,
    raastEnabled: false,
    favourite: false,
  },
  {
    id: 'sana-khan',
    name: 'Sana Khan',
    initials: 'SK',
    tone: 'cyan',
    bank: 'Bank Alfalah',
    maskedNumber: '•••• 8834',
    iban: 'PK55ALFH0006677889908834',
    transferLimit: 150_000,
    raastEnabled: true,
    favourite: false,
  },
]

export const billers: Biller[] = [
  {
    id: 'k-electric',
    name: 'K-Electric',
    category: 'Electricity',
    consumerNumber: '04 21 3389 4410',
    dueDate: '28 Mar 2024',
    amountDue: 18_450,
    tone: 'accent',
  },
  {
    id: 'ssgc',
    name: 'Sui Southern Gas',
    category: 'Gas',
    consumerNumber: '11 5522 8890 3',
    dueDate: '01 Apr 2024',
    amountDue: 6_320,
    tone: 'brand',
  },
  {
    id: 'ptcl',
    name: 'PTCL Broadband',
    category: 'Internet',
    consumerNumber: '021 35870021',
    dueDate: '04 Apr 2024',
    amountDue: 4_899,
    tone: 'sky',
  },
  {
    id: 'jazz',
    name: 'Jazz Postpaid',
    category: 'Mobile',
    consumerNumber: '0300 1234567',
    dueDate: '07 Apr 2024',
    amountDue: 3_150,
    tone: 'positive',
  },
  {
    id: 'kwsb',
    name: 'Karachi Water Board',
    category: 'Water',
    consumerNumber: '07 4412 9987',
    dueDate: '10 Apr 2024',
    amountDue: 2_400,
    tone: 'sky',
  },
  {
    id: 'nayatel',
    name: 'Nayatel Fibre',
    category: 'Internet',
    consumerNumber: '051 1119988',
    dueDate: '12 Apr 2024',
    amountDue: 7_500,
    tone: 'brand',
  },
]

export const cards: BankCard[] = [
  {
    id: 'card-debit-visa',
    accountId: 'acc-current',
    label: 'Everyday Debit',
    kind: 'debit',
    network: 'VISA',
    holder: 'AYESHA SIDDIQUI',
    maskedNumber: '•••• •••• •••• 4821',
    expiry: '09/27',
    pin: '4417',
    status: 'active',
    ecommerceEnabled: true,
    contactlessEnabled: true,
    internationalEnabled: false,
    dailyLimit: 150_000,
    maxLimit: 500_000,
    spentToday: 8_624,
    gradient: 'from-brand-600 via-brand-700 to-brand-900',
  },
  {
    id: 'card-paypak',
    accountId: 'acc-savings',
    label: 'Savings PayPak',
    kind: 'debit',
    network: 'PayPak',
    holder: 'AYESHA SIDDIQUI',
    maskedNumber: '•••• •••• •••• 7130',
    expiry: '05/28',
    pin: '9032',
    status: 'active',
    ecommerceEnabled: false,
    contactlessEnabled: true,
    internationalEnabled: false,
    dailyLimit: 75_000,
    maxLimit: 300_000,
    spentToday: 0,
    gradient: 'from-ink via-[#1e2c4c] to-[#0d1831]',
  },
  {
    id: 'card-credit-gold',
    accountId: 'acc-current',
    label: 'Gold Credit',
    kind: 'credit',
    network: 'Mastercard',
    holder: 'AYESHA SIDDIQUI',
    maskedNumber: '•••• •••• •••• 6604',
    expiry: '11/26',
    pin: '2288',
    status: 'active',
    ecommerceEnabled: true,
    contactlessEnabled: true,
    internationalEnabled: true,
    dailyLimit: 300_000,
    maxLimit: 800_000,
    spentToday: 24_990,
    gradient: 'from-brand-800 via-brand-500 to-accent-400',
  },
]

export const spendingCategories: SpendingCategory[] = [
  { id: 'housing', label: 'Housing', amount: 98_000, percent: 45, colorClass: 'bg-brand-600', hex: '#3d3ac7' },
  {
    id: 'groceries',
    label: 'Groceries & dining',
    amount: 45_400,
    percent: 21,
    colorClass: 'bg-positive-400',
    hex: '#059669',
  },
  { id: 'utilities', label: 'Utilities', amount: 32_400, percent: 15, colorClass: 'bg-accent-400', hex: '#06b6d4' },
  { id: 'shopping', label: 'Shopping', amount: 24_990, percent: 12, colorClass: 'bg-[#8b5cf6]', hex: '#8b5cf6' },
  { id: 'transport', label: 'Transport', amount: 15_250, percent: 7, colorClass: 'bg-[#f59e0b]', hex: '#f59e0b' },
]

export const merchants: Merchant[] = [
  {
    id: 'sindhi-kitchen',
    name: 'Sindhi Kitchen',
    city: 'Karachi',
    category: 'Restaurant',
    merchantId: 'RAAST-P2M-88214',
  },
  {
    id: 'chase-up',
    name: 'Chase Up Superstore',
    city: 'Karachi',
    category: 'Retail',
    merchantId: 'RAAST-P2M-31099',
  },
  {
    id: 'gloria-jeans',
    name: 'Gloria Jean Coffees',
    city: 'Lahore',
    category: 'Cafe',
    merchantId: 'RAAST-P2M-77410',
  },
]

export const branches: Branch[] = [
  {
    id: 'clifton',
    name: 'Clifton Branch',
    type: 'branch',
    address: 'Block 5, Kehkashan, Clifton',
    city: 'Karachi',
    timings: 'Mon–Fri, 9:00 AM – 5:00 PM',
    services: ['Cash', 'Lockers', 'Foreign exchange'],
    distanceKm: 1.2,
  },
  {
    id: 'dolmen-atm',
    name: 'Dolmen Mall ATM',
    type: 'atm',
    address: 'Dolmen Mall, Marine Drive, Clifton',
    city: 'Karachi',
    timings: 'Open 24 hours',
    services: ['Cash withdrawal', 'Balance enquiry'],
    distanceKm: 2.4,
  },
  {
    id: 'shahrah-e-faisal',
    name: 'Shahrah-e-Faisal Branch',
    type: 'branch',
    address: 'PECHS Block 6, Shahrah-e-Faisal',
    city: 'Karachi',
    timings: 'Mon–Fri, 9:00 AM – 5:00 PM',
    services: ['Cash', 'Cheque clearing', 'Account opening'],
    distanceKm: 5.8,
  },
  {
    id: 'gulberg',
    name: 'Gulberg Branch',
    type: 'branch',
    address: 'Main Boulevard, Gulberg III',
    city: 'Lahore',
    timings: 'Mon–Fri, 9:00 AM – 5:00 PM',
    services: ['Cash', 'Lockers', 'Trade finance'],
    distanceKm: 1042,
  },
  {
    id: 'blue-area-atm',
    name: 'Blue Area ATM',
    type: 'atm',
    address: 'Jinnah Avenue, Blue Area',
    city: 'Islamabad',
    timings: 'Open 24 hours',
    services: ['Cash withdrawal', 'Cash deposit'],
    distanceKm: 1128,
  },
  {
    id: 'saddar-branch',
    name: 'Saddar Branch',
    type: 'branch',
    address: 'Zaibunnisa Street, Saddar',
    city: 'Karachi',
    timings: 'Mon–Fri, 9:00 AM – 5:00 PM',
    services: ['Cash', 'Remittances'],
    distanceKm: 7.1,
  },
]

export const notifications: AppNotification[] = [
  {
    id: 'n-debit-imtiaz',
    kind: 'transaction',
    title: 'Card spend of PKR 8,624.00',
    body: 'Imtiaz Super Market • Everyday Debit •••• 4821',
    timestamp: daysAgo(0, 10, 43),
    read: false,
  },
  {
    id: 'n-login',
    kind: 'security',
    title: 'New sign-in detected',
    body: 'Chrome on Windows, Karachi. If this was not you, secure your account.',
    timestamp: daysAgo(0, 8, 12),
    read: false,
  },
  {
    id: 'n-salary',
    kind: 'transaction',
    title: 'Salary credited: PKR 428,000.00',
    body: 'Habib Textiles Payroll • Everyday Current •••• 4821',
    timestamp: daysAgo(1, 9, 1),
    read: false,
  },
  {
    id: 'n-bill-due',
    kind: 'system',
    title: 'K-Electric bill due in 7 days',
    body: 'PKR 18,450.00 due on 28 Mar 2024. Set a standing instruction to never miss it.',
    timestamp: daysAgo(1, 7, 30),
    read: true,
  },
  {
    id: 'n-raast',
    kind: 'promo',
    title: 'Raast transfers are free',
    body: 'Send money instantly to any bank in Pakistan at zero cost.',
    timestamp: daysAgo(3, 13, 0),
    read: true,
  },
  {
    id: 'n-limit',
    kind: 'security',
    title: 'Daily limit updated',
    body: 'Your Everyday Debit daily limit was changed to PKR 150,000.',
    timestamp: daysAgo(6, 17, 45),
    read: true,
  },
]

export const ASSISTANT_REPLIES: ReadonlyArray<{ match: RegExp; reply: string }> = [
  {
    match: /balance|kitna|how much/i,
    reply:
      'Your Everyday Current account is at PKR 2,468,042.00, with PKR 2,431,540.00 available right now. Savings adds another PKR 1,186,500.00.',
  },
  {
    match: /transfer|send|ibft|raast/i,
    reply:
      'I can take you to Send money. Transfers to saved beneficiaries go out instantly over Raast, free of charge — just pick a payee and an amount.',
  },
  {
    match: /spend|spent|budget|month/i,
    reply:
      'You have spent PKR 216,040.00 this month — 12.8% less than February. Housing is your largest category at PKR 98,000.00.',
  },
  {
    match: /atm|branch|near/i,
    reply:
      'The closest point is Clifton Branch, 1.2 km away, open Mon–Fri 9:00 AM – 5:00 PM. Dolmen Mall ATM is 2.4 km away and open 24 hours.',
  },
  {
    match: /bill|electric|gas|internet/i,
    reply:
      'Your K-Electric bill of PKR 18,450.00 is due on 28 Mar 2024. I can open Pay a bill so you can settle it now or schedule it.',
  },
  {
    match: /card|freeze|block|pin/i,
    reply:
      'You have three cards. Everyday Debit •••• 4821 is active with a PKR 150,000 daily limit — you can freeze it or reveal the PIN from the Cards screen.',
  },
]

export const ASSISTANT_FALLBACK =
  'I have noted that down. I can help with balances, transfers, bill payments, card controls and finding a branch — everything stays inside this demo.'
