import { useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, BarChart3, Bell, CalendarDays, Check, ChevronRight, CircleHelp, CreditCard, Eye, EyeOff, Fingerprint, Home, LockKeyhole, MoreHorizontal, Plus, Send, ShieldCheck, Sparkles, UserRound, WalletCards, X } from 'lucide-react'
import './App.css'

const transactions = [
  { name: 'Whole Foods Market', category: 'Groceries', date: 'Today, 10:42 AM', amount: '-$86.24', icon: 'W', tone: 'green' },
  { name: 'Northstar Payroll', category: 'Salary', date: 'Yesterday, 9:00 AM', amount: '+$4,280.00', icon: 'N', tone: 'blue' },
  { name: 'West Elm', category: 'Shopping', date: 'Mar 18, 2:15 PM', amount: '-$249.99', icon: 'W', tone: 'orange' },
  { name: 'Spotify Premium', category: 'Subscriptions', date: 'Mar 17, 12:04 PM', amount: '-$10.99', icon: 'S', tone: 'violet' },
]
const contacts = [{ name: 'Jamie Lee', initials: 'JL', tone: 'lavender' }, { name: 'Morgan K.', initials: 'MK', tone: 'peach' }, { name: 'Taylor R.', initials: 'TR', tone: 'mint' }, { name: 'Chris D.', initials: 'CD', tone: 'sky' }, { name: 'Add new', initials: '+', tone: 'new' }]

function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false)
  const [currentPage, setCurrentPage] = useState('home')
  const [showBalance, setShowBalance] = useState(true)
  const [showPassword, setShowPassword] = useState(false)
  const [isFrozen, setIsFrozen] = useState(false)
  const [chatOpen, setChatOpen] = useState(false)
  const [messages, setMessages] = useState([])
  const [transferSent, setTransferSent] = useState(false)
  // Replace this local response with the authenticated API/LLM request when the assistant backend is ready.
  const sendChat = (text) => setMessages((current) => [...current, { from: 'user', text }, { from: 'assistant', text: `Here is what I found for “${text.toLowerCase()}”. Your accounts are looking healthy and up to date.` }])

  if (!isAuthenticated) return <main className="auth-shell"><div className="auth-brand"><span className="brand-mark">N</span><span>northstar</span></div><div className="auth-layout"><section className="auth-copy"><p className="eyebrow">PERSONAL BANKING, REIMAGINED</p><h1>Money that moves<br /><em>with you.</em></h1><p className="auth-intro">A clearer view of your everyday finances, built to help you make confident decisions.</p><div className="trust-row"><ShieldCheck size={18} /><span>Bank-grade security, always on.</span></div></section><section className="login-panel"><div className="login-heading"><div><p className="eyebrow">WELCOME BACK</p><h2>Sign in to Northstar</h2></div><div className="secure-icon"><LockKeyhole size={18} /></div></div><form onSubmit={(event) => { event.preventDefault(); setIsAuthenticated(true) }}><label>Email or username<input type="text" placeholder="alex@example.com" /></label><label>Password<div className="input-with-action"><input type={showPassword ? 'text' : 'password'} placeholder="Enter your password" /><button type="button" className="field-action" aria-label="Toggle password visibility" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label><div className="form-meta"><label className="check-label"><input type="checkbox" defaultChecked /> <span>Remember me</span></label><button type="button" className="text-button">Forgot password?</button></div><button className="primary-button login-button" type="submit">Sign in <ArrowUpRight size={18} /></button><button type="button" className="biometric-button" onClick={() => setIsAuthenticated(true)}><Fingerprint size={19} /> Use biometric login</button></form><p className="login-footer">New to Northstar? <button className="text-button">Open an account</button></p></section></div><div className="auth-bottom"><span>FDIC insured • Member since 2012</span><span><CircleHelp size={14} /> Help center</span></div></main>

  return (
    <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">N</span><span>northstar</span></div><div className="topbar-actions"><button className="icon-button notification" aria-label="Notifications"><Bell size={20} /><span>3</span></button><button className="profile-button" onClick={() => setCurrentPage('profile')}><span className="avatar">AS</span><span className="profile-name">Alex Smith</span><ChevronRight size={16} /></button></div></header><div className="app-content"><section className="page-header"><div><p className="eyebrow">THURSDAY, MARCH 21, 2024</p><h1>{currentPage === 'home' ? <>Good morning, Alex <span className="wave">✦</span></> : pageTitle(currentPage)}</h1></div><button className="small-date"><CalendarDays size={16} /> This month <ChevronRight size={14} /></button></section>{currentPage === 'home' && <HomePage showBalance={showBalance} setShowBalance={setShowBalance} setCurrentPage={setCurrentPage} />}{currentPage === 'cards' && <CardsPage isFrozen={isFrozen} setIsFrozen={setIsFrozen} />}{currentPage === 'analytics' && <AnalyticsPage />}{currentPage === 'transfers' && <TransfersPage transferSent={transferSent} setTransferSent={setTransferSent} />}{currentPage === 'profile' && <ProfilePage logout={() => { setIsAuthenticated(false); setCurrentPage('home') }} />}</div><nav className="bottom-nav">{[['home', Home, 'Overview'], ['cards', WalletCards, 'Cards'], ['analytics', BarChart3, 'Insights'], ['transfers', Send, 'Move money']].map(([id, Icon, label]) => <button key={id} className={currentPage === id ? 'active' : ''} onClick={() => setCurrentPage(id)}><Icon size={19} /><span>{label}</span></button>)}</nav><button className="assistant-fab" aria-label="Open financial assistant" onClick={() => setChatOpen(true)}><Sparkles size={21} /></button>{chatOpen && <ChatModal messages={messages} onClose={() => setChatOpen(false)} onSend={sendChat} />}</main>
  )
}

const pageTitle = (page) => ({ cards: 'Your cards', analytics: 'Spending insights', transfers: 'Move your money', profile: 'Profile & settings' }[page])
function HomePage({ showBalance, setShowBalance, setCurrentPage }) { return <><section className="balance-grid"><div className="balance-card"><div className="balance-top"><span className="card-label">TOTAL BALANCE <button className="inline-icon" onClick={() => setShowBalance(!showBalance)}>{showBalance ? <Eye size={16} /> : <EyeOff size={16} />}</button></span><span className="balance-up">+8.4% <ArrowUpRight size={13} /></span></div><div className="balance-amount">{showBalance ? '$24,680.42' : '••••••••'}</div><div className="balance-bottom"><span>Everyday Checking<br /><strong>•••• 4821</strong></span><span className="visa">VISA</span></div></div><div className="snapshot-card"><div className="section-title"><span>Monthly snapshot</span><MoreHorizontal size={19} /></div><div className="snapshot-row"><div><small>Income</small><strong className="positive">+$6,840</strong></div><div><small>Spent</small><strong>-$2,160</strong></div></div><div className="progress"><span /></div><small className="muted">$4,680 left of your $6,840 income</small></div></section><section className="quick-actions"><QuickAction icon={Send} label="Send" onClick={() => setCurrentPage('transfers')} /><QuickAction icon={ArrowDownLeft} label="Request" onClick={() => setCurrentPage('transfers')} /><QuickAction icon={CreditCard} label="Pay bills" onClick={() => setCurrentPage('transfers')} /><QuickAction icon={Plus} label="Top up" onClick={() => setCurrentPage('transfers')} /></section><section className="content-section"><div className="section-heading"><div><p className="eyebrow">QUICK TRANSFER</p><h2>Send money to</h2></div><button className="text-button">Manage <ChevronRight size={14} /></button></div><div className="contact-scroll">{contacts.map((contact) => <button className="contact" key={contact.name} onClick={() => setCurrentPage('transfers')}><span className={`contact-avatar ${contact.tone}`}>{contact.initials}</span><span>{contact.name}</span></button>)}</div></section><section className="content-section transactions"><div className="section-heading"><div><p className="eyebrow">ACTIVITY</p><h2>Recent transactions</h2></div><button className="text-button">See all <ChevronRight size={14} /></button></div>{transactions.map((transaction) => <div className="transaction" key={transaction.name}><span className={`transaction-icon ${transaction.tone}`}>{transaction.icon}</span><div className="transaction-info"><strong>{transaction.name}</strong><small>{transaction.category} <span>•</span> {transaction.date}</small></div><strong className={transaction.amount.startsWith('+') ? 'positive' : ''}>{transaction.amount}</strong></div>)}</section></> }
function QuickAction({ icon: Icon, label, onClick }) { return <button className="quick-action" onClick={onClick}><span><Icon size={19} /></span>{label}</button> }
function CardsPage({ isFrozen, setIsFrozen }) { return <div className="cards-page"><section className="debit-card"><div className="card-top"><span className="brand-light">northstar</span><span>VISA</span></div><div className="chip" /><div className="card-number">•••• &nbsp; •••• &nbsp; •••• &nbsp; 4821</div><div className="card-bottom"><span>Alex Smith</span><span>09/27</span></div></section><div className="card-controls"><div className="control-row"><div><strong>Freeze card</strong><small>Temporarily disable all transactions</small></div><button className={`toggle ${isFrozen ? 'on' : ''}`} onClick={() => setIsFrozen(!isFrozen)}><span /></button></div><div className="control-row"><div><strong>View PIN</strong><small>Reveal your 4-digit card PIN</small></div><button className="round-control"><Eye size={17} /></button></div></div><section className="limit-card"><div className="section-title"><div><p className="eyebrow">DAILY SPENDING LIMIT</p><h2>$2,500</h2></div><span className="limit-badge">72% available</span></div><input type="range" defaultValue="72" /><div className="limit-labels"><span>$0</span><span>$5,000</span></div></section></div> }
function AnalyticsPage() { return <div className="analytics-page"><section className="insight-hero"><div><p className="eyebrow">MARCH SPENDING</p><h2>$2,160.40</h2><p className="positive">↓ 12.8% from last month</p></div><div className="donut"><span>62%<small>of budget</small></span></div></section><section className="category-list"><div className="section-heading"><div><p className="eyebrow">WHERE IT GOES</p><h2>Spending by category</h2></div><button className="text-button">Details <ChevronRight size={14} /></button></div>{[['Housing', '$980.00', '45%', 'blue'], ['Food & dining', '$460.30', '21%', 'green'], ['Shopping', '$320.10', '15%', 'orange'], ['Transport', '$210.00', '10%', 'violet']].map(([name, amount, width, color]) => <div className="category" key={name}><div className="category-meta"><span>{name}</span><strong>{amount}</strong></div><div className="category-bar"><span className={color} style={{ width }} /></div></div>)}</section><section className="budget-card"><div><p className="eyebrow">MONTHLY BUDGET</p><h2>You're on track</h2><p className="muted">$1,639.60 remaining this month</p></div><BarChart3 size={32} /></section></div> }
function TransfersPage({ transferSent, setTransferSent }) { return <div className="transfer-page"><section className="transfer-form"><div className="section-heading"><div><p className="eyebrow">NEW TRANSFER</p><h2>Send money</h2></div><span className="secure-pill"><ShieldCheck size={14} /> Secure</span></div>{transferSent ? <div className="success-state"><span><Check size={25} /></span><h2>Transfer scheduled</h2><p>Your $250.00 transfer to Jamie Lee is on its way.</p><button className="primary-button" onClick={() => setTransferSent(false)}>Make another transfer</button></div> : <form onSubmit={(event) => { event.preventDefault(); setTransferSent(true) }}><label>From<input value="Everyday Checking •••• 4821" readOnly /></label><label>To<select defaultValue="Jamie"><option value="Jamie">Jamie Lee •••• 2091</option><option value="Morgan">Morgan K. •••• 7712</option></select></label><label>Amount<div className="amount-input"><span>$</span><input defaultValue="250.00" type="number" /></div></label><button className="primary-button" type="submit">Review transfer <ArrowUpRight size={17} /></button></form>}</section><section className="scheduled"><div className="section-heading"><div><p className="eyebrow">UPCOMING</p><h2>Scheduled payments</h2></div><button className="round-control"><Plus size={17} /></button></div><div className="scheduled-item"><span className="bill-icon">◎</span><div><strong>City Power & Light</strong><small>Due Mar 28 <span>•</span> Utilities</small></div><strong>$84.20</strong></div><div className="scheduled-item"><span className="bill-icon wifi">⌁</span><div><strong>SkyNet Internet</strong><small>Due Apr 01 <span>•</span> Internet</small></div><strong>$65.00</strong></div></section></div> }
function ProfilePage({ logout }) { return <div className="profile-page"><div className="profile-hero"><span className="large-avatar">AS</span><div><h2>Alex Smith</h2><p className="muted">alex.smith@example.com</p></div></div><div className="settings-list"><button><UserRound size={19} /> Personal details <ChevronRight size={16} /></button><button><ShieldCheck size={19} /> Security & privacy <ChevronRight size={16} /></button><button><Bell size={19} /> Notifications <ChevronRight size={16} /></button><button className="logout" onClick={logout}><ArrowUpRight size={19} /> Log out</button></div></div> }
function ChatModal({ messages, onClose, onSend }) { const [input, setInput] = useState(''); const submit = (text) => { onSend(text); setInput('') }; return <div className="chat-backdrop" onClick={onClose}><section className="chat-modal" onClick={(event) => event.stopPropagation()}><header><div><span className="assistant-icon"><Sparkles size={17} /></span><div><strong>Northstar assistant</strong><small>Always here to help</small></div></div><button className="icon-button" onClick={onClose}><X size={19} /></button></header><div className="chat-body"><div className="assistant-message">Hi Alex, I’m your financial assistant. What can I help you with today?</div>{messages.map((message, index) => <div className={`chat-message ${message.from}`} key={`${message.text}-${index}`}>{message.text}</div>)}</div><div className="suggestions">{['Check my balance', 'Transfer money', 'Show monthly spend'].map((suggestion) => <button key={suggestion} onClick={() => submit(suggestion)}>{suggestion}</button>)}</div><form className="chat-input" onSubmit={(event) => { event.preventDefault(); if (input.trim()) submit(input.trim()) }}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask anything about your money" /><button aria-label="Send message"><Send size={17} /></button></form></section></div> }

export default App
