import { useEffect, useState } from 'react'
import { ArrowDownLeft, ArrowLeft, ArrowUpRight, BarChart3, Bell, CalendarDays, Check, ChevronRight, CircleHelp, CreditCard, Eye, EyeOff, Fingerprint, Home, LockKeyhole, MoreHorizontal, Plus, Receipt, Send, ShieldCheck, Sparkles, UserRound, WalletCards, X } from 'lucide-react'
import './App.css'

const transactions = [
  { id: 'whole-foods', name: 'Whole Foods Market', category: 'Groceries', date: 'Today, 10:42 AM', amount: '-$86.24', icon: 'W', tone: 'green' },
  { id: 'northstar-payroll', name: 'Northstar Payroll', category: 'Salary', date: 'Yesterday, 9:00 AM', amount: '+$4,280.00', icon: 'N', tone: 'blue' },
  { id: 'west-elm', name: 'West Elm', category: 'Shopping', date: 'Mar 18, 2:15 PM', amount: '-$249.99', icon: 'W', tone: 'orange' },
  { id: 'spotify', name: 'Spotify Premium', category: 'Subscriptions', date: 'Mar 17, 12:04 PM', amount: '-$10.99', icon: 'S', tone: 'violet' },
]
const contacts = [
  { id: 'jamie-lee', name: 'Jamie Lee', initials: 'JL', tone: 'lavender', account: '•••• 2091' },
  { id: 'morgan-k', name: 'Morgan K.', initials: 'MK', tone: 'peach', account: '•••• 7712' },
  { id: 'taylor-r', name: 'Taylor R.', initials: 'TR', tone: 'mint', account: '•••• 3480' },
  { id: 'chris-d', name: 'Chris D.', initials: 'CD', tone: 'sky', account: '•••• 6155' },
  { id: 'add-new', name: 'Add new', initials: '+', tone: 'new' },
]
const payees = contacts.filter((contact) => contact.account)
const billers = [
  { id: 'city-power', name: 'City Power & Light', category: 'Utilities', due: 'Mar 28', amount: '84.20', glyph: '◎', tone: '' },
  { id: 'skynet-internet', name: 'SkyNet Internet', category: 'Internet', due: 'Apr 01', amount: '65.00', glyph: '⌁', tone: 'wifi' },
  { id: 'metro-water', name: 'Metro Water', category: 'Utilities', due: 'Apr 04', amount: '38.60', glyph: '◍', tone: '' },
]

const screenTitles = { 'cards-screen': 'Your cards', 'analytics-screen': 'Spending insights', 'sendmoney-screen': 'Send money', 'sendmoney-confirm-screen': 'Review transfer', 'sendmoney-success-screen': 'Transfer sent', 'paybill-screen': 'Pay a bill', 'paybill-confirm-screen': 'Review payment', 'paybill-success-screen': 'Bill paid', 'profile-screen': 'Profile & settings' }
const money = (value) => `$${Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const navTabFor = (screen) => (screen.startsWith('sendmoney') || screen.startsWith('paybill') ? 'sendmoney-screen' : screen)

// Single integration point for the voice agent. Every screen transition — login and logout
// included — flows through the `screen` value in App, so this fires exactly once per
// transition. If the agent expects postMessage instead of a DOM event, change it here.
const broadcastScreen = (screen) => {
  window.__AGENT_SCREEN__ = screen
  window.dispatchEvent(new CustomEvent('AGENT_SCREEN_CHANGE', { detail: { screen } }))
}

function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false)
  const [page, setPage] = useState('home-screen')
  const [showBalance, setShowBalance] = useState(true)
  const [showPassword, setShowPassword] = useState(false)
  const [isFrozen, setIsFrozen] = useState(false)
  const [chatOpen, setChatOpen] = useState(false)
  const [messages, setMessages] = useState([])
  const [transfer, setTransfer] = useState({ contactId: 'jamie-lee', amount: '250.00' })
  const [bill, setBill] = useState({ billerId: 'city-power', amount: '84.20' })
  const screen = isAuthenticated ? page : 'login-screen'
  useEffect(() => { broadcastScreen(screen) }, [screen])
  // Replace this local response with the authenticated API/LLM request when the assistant backend is ready.
  const sendChat = (text) => setMessages((current) => [...current, { from: 'user', text }, { from: 'assistant', text: `Here is what I found for “${text.toLowerCase()}”. Your accounts are looking healthy and up to date.` }])
  const startTransfer = (contactId) => { if (contactId) setTransfer((current) => ({ ...current, contactId })); setPage('sendmoney-screen') }
  const startBill = (billerId) => { const target = billers.find((entry) => entry.id === billerId); if (target) setBill({ billerId: target.id, amount: target.amount }); setPage('paybill-screen') }

  if (!isAuthenticated) return <main className="auth-shell" data-agent-screen="login-screen"><div className="auth-brand"><span className="brand-mark">N</span><span>northstar</span></div><div className="auth-layout"><section className="auth-copy"><p className="eyebrow">PERSONAL BANKING, REIMAGINED</p><h1>Money that moves<br /><em>with you.</em></h1><p className="auth-intro">A clearer view of your everyday finances, built to help you make confident decisions.</p><div className="trust-row"><ShieldCheck size={18} /><span>Bank-grade security, always on.</span></div></section><section className="login-panel"><div className="login-heading"><div><p className="eyebrow">WELCOME BACK</p><h2>Sign in to Northstar</h2></div><div className="secure-icon"><LockKeyhole size={18} /></div></div><form onSubmit={(event) => { event.preventDefault(); setIsAuthenticated(true) }}><label>Email or username<input data-agent-id="login-email-input" type="text" placeholder="alex@example.com" /></label><label>Password<div className="input-with-action"><input data-agent-id="login-password-input" type={showPassword ? 'text' : 'password'} placeholder="Enter your password" /><button data-agent-id="login-password-toggle" type="button" className="field-action" aria-label="Toggle password visibility" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label><div className="form-meta"><label className="check-label"><input data-agent-id="login-remember-checkbox" type="checkbox" defaultChecked /> <span>Remember me</span></label><button data-agent-id="login-forgot-password" type="button" className="text-button">Forgot password?</button></div><button data-agent-id="login-submit" className="primary-button login-button" type="submit">Sign in <ArrowUpRight size={18} /></button><button data-agent-id="login-biometric" type="button" className="biometric-button" onClick={() => setIsAuthenticated(true)}><Fingerprint size={19} /> Use biometric login</button></form><p className="login-footer">New to Northstar? <button data-agent-id="login-open-account" className="text-button">Open an account</button></p></section></div><div className="auth-bottom"><span>FDIC insured • Member since 2012</span><span><CircleHelp size={14} /> Help center</span></div></main>

  return (
    <main className="app-shell" data-agent-screen={screen}>
      <header className="topbar"><div className="brand"><span className="brand-mark">N</span><span>northstar</span></div><div className="topbar-actions"><button data-agent-id="nav-notifications" className="icon-button notification" aria-label="Notifications"><Bell size={20} /><span>3</span></button><button data-agent-id="nav-profile" className="profile-button" onClick={() => setPage('profile-screen')}><span className="avatar">AS</span><span className="profile-name">Alex Smith</span><ChevronRight size={16} /></button></div></header>
      <div className="app-content">
        <section className="page-header"><div><p className="eyebrow">THURSDAY, MARCH 21, 2024</p><h1>{screen === 'home-screen' ? <>Good morning, Alex <span className="wave">✦</span></> : screenTitles[screen]}</h1></div><button data-agent-id="header-date-range" className="small-date"><CalendarDays size={16} /> This month <ChevronRight size={14} /></button></section>
        {screen === 'home-screen' && <HomePage showBalance={showBalance} setShowBalance={setShowBalance} startTransfer={startTransfer} startBill={startBill} />}
        {screen === 'cards-screen' && <CardsPage isFrozen={isFrozen} setIsFrozen={setIsFrozen} />}
        {screen === 'analytics-screen' && <AnalyticsPage />}
        {screen === 'sendmoney-screen' && <SendMoneyPage transfer={transfer} setTransfer={setTransfer} go={setPage} />}
        {screen === 'sendmoney-confirm-screen' && <SendMoneyConfirmPage transfer={transfer} go={setPage} />}
        {screen === 'sendmoney-success-screen' && <SendMoneySuccessPage transfer={transfer} go={setPage} />}
        {screen === 'paybill-screen' && <PayBillPage bill={bill} setBill={setBill} go={setPage} />}
        {screen === 'paybill-confirm-screen' && <PayBillConfirmPage bill={bill} go={setPage} />}
        {screen === 'paybill-success-screen' && <PayBillSuccessPage bill={bill} go={setPage} />}
        {screen === 'profile-screen' && <ProfilePage logout={() => { setIsAuthenticated(false); setPage('home-screen') }} />}
      </div>
      <nav className="bottom-nav">{[['home-screen', Home, 'Overview', 'nav-home'], ['cards-screen', WalletCards, 'Cards', 'nav-cards'], ['analytics-screen', BarChart3, 'Insights', 'nav-analytics'], ['sendmoney-screen', Send, 'Move money', 'nav-sendmoney']].map(([id, Icon, label, agentId]) => <button data-agent-id={agentId} key={id} className={navTabFor(screen) === id ? 'active' : ''} onClick={() => setPage(id)}><Icon size={19} /><span>{label}</span></button>)}</nav>
      <button data-agent-id="assistant-fab" className="assistant-fab" aria-label="Open financial assistant" onClick={() => setChatOpen(true)}><Sparkles size={21} /></button>
      {chatOpen && <ChatModal messages={messages} onClose={() => setChatOpen(false)} onSend={sendChat} />}
    </main>
  )
}

function HomePage({ showBalance, setShowBalance, startTransfer, startBill }) { return <><section className="balance-grid"><div className="balance-card"><div className="balance-top"><span className="card-label">TOTAL BALANCE <button data-agent-id="home-balance-toggle" className="inline-icon" onClick={() => setShowBalance(!showBalance)}>{showBalance ? <Eye size={16} /> : <EyeOff size={16} />}</button></span><span className="balance-up">+8.4% <ArrowUpRight size={13} /></span></div><div className="balance-amount">{showBalance ? '$24,680.42' : '••••••••'}</div><div className="balance-bottom"><span>Everyday Checking<br /><strong>•••• 4821</strong></span><span className="visa">VISA</span></div></div><div className="snapshot-card"><div className="section-title"><span>Monthly snapshot</span><MoreHorizontal size={19} /></div><div className="snapshot-row"><div><small>Income</small><strong className="positive">+$6,840</strong></div><div><small>Spent</small><strong>-$2,160</strong></div></div><div className="progress"><span /></div><small className="muted">$4,680 left of your $6,840 income</small></div></section><section className="quick-actions"><QuickAction agentId="home-quick-action-send" icon={Send} label="Send" onClick={() => startTransfer()} /><QuickAction agentId="home-quick-action-request" icon={ArrowDownLeft} label="Request" onClick={() => startTransfer()} /><QuickAction agentId="home-quick-action-paybill" icon={CreditCard} label="Pay bills" onClick={() => startBill()} /><QuickAction agentId="home-quick-action-topup" icon={Plus} label="Top up" onClick={() => startTransfer()} /></section><section className="content-section"><div className="section-heading"><div><p className="eyebrow">QUICK TRANSFER</p><h2>Send money to</h2></div><button data-agent-id="home-contacts-manage" className="text-button">Manage <ChevronRight size={14} /></button></div><div className="contact-scroll">{contacts.map((contact) => <button data-agent-id={`home-contact-${contact.id}`} className="contact" key={contact.id} onClick={() => startTransfer(contact.account ? contact.id : undefined)}><span className={`contact-avatar ${contact.tone}`}>{contact.initials}</span><span>{contact.name}</span></button>)}</div></section><section className="content-section transactions"><div className="section-heading"><div><p className="eyebrow">ACTIVITY</p><h2>Recent transactions</h2></div><button data-agent-id="home-transactions-see-all" className="text-button">See all <ChevronRight size={14} /></button></div>{transactions.map((transaction) => <div data-agent-id={`home-transaction-${transaction.id}`} className="transaction" key={transaction.id}><span className={`transaction-icon ${transaction.tone}`}>{transaction.icon}</span><div className="transaction-info"><strong>{transaction.name}</strong><small>{transaction.category} <span>•</span> {transaction.date}</small></div><strong className={transaction.amount.startsWith('+') ? 'positive' : ''}>{transaction.amount}</strong></div>)}</section></> }
function QuickAction({ icon: Icon, label, onClick, agentId }) { return <button data-agent-id={agentId} className="quick-action" onClick={onClick}><span><Icon size={19} /></span>{label}</button> }
function CardsPage({ isFrozen, setIsFrozen }) { return <div className="cards-page"><section className="debit-card"><div className="card-top"><span className="brand-light">northstar</span><span>VISA</span></div><div className="chip" /><div className="card-number">•••• &nbsp; •••• &nbsp; •••• &nbsp; 4821</div><div className="card-bottom"><span>Alex Smith</span><span>09/27</span></div></section><div className="card-controls"><div className="control-row"><div><strong>Freeze card</strong><small>Temporarily disable all transactions</small></div><button data-agent-id="cards-freeze-toggle" className={`toggle ${isFrozen ? 'on' : ''}`} onClick={() => setIsFrozen(!isFrozen)}><span /></button></div><div className="control-row"><div><strong>View PIN</strong><small>Reveal your 4-digit card PIN</small></div><button data-agent-id="cards-view-pin" className="round-control"><Eye size={17} /></button></div></div><section className="limit-card"><div className="section-title"><div><p className="eyebrow">DAILY SPENDING LIMIT</p><h2>$2,500</h2></div><span className="limit-badge">72% available</span></div><input data-agent-id="cards-limit-slider" type="range" defaultValue="72" /><div className="limit-labels"><span>$0</span><span>$5,000</span></div></section></div> }
function AnalyticsPage() { return <div className="analytics-page"><section className="insight-hero"><div><p className="eyebrow">MARCH SPENDING</p><h2>$2,160.40</h2><p className="positive">↓ 12.8% from last month</p></div><div className="donut"><span>62%<small>of budget</small></span></div></section><section className="category-list"><div className="section-heading"><div><p className="eyebrow">WHERE IT GOES</p><h2>Spending by category</h2></div><button data-agent-id="analytics-category-details" className="text-button">Details <ChevronRight size={14} /></button></div>{[['housing', 'Housing', '$980.00', '45%', 'blue'], ['food', 'Food & dining', '$460.30', '21%', 'green'], ['shopping', 'Shopping', '$320.10', '15%', 'orange'], ['transport', 'Transport', '$210.00', '10%', 'violet']].map(([id, name, amount, width, color]) => <div data-agent-id={`analytics-category-${id}`} className="category" key={id}><div className="category-meta"><span>{name}</span><strong>{amount}</strong></div><div className="category-bar"><span className={color} style={{ width }} /></div></div>)}</section><section className="budget-card"><div><p className="eyebrow">MONTHLY BUDGET</p><h2>You&apos;re on track</h2><p className="muted">$1,639.60 remaining this month</p></div><BarChart3 size={32} /></section></div> }

function ReviewRow({ label, value, agentId }) { return <div className="review-row" data-agent-id={agentId}><span>{label}</span><strong>{value}</strong></div> }

function SendMoneyPage({ transfer, setTransfer, go }) {
  const payee = payees.find((contact) => contact.id === transfer.contactId) || payees[0]
  return <div className="transfer-page"><section className="transfer-form"><div className="section-heading"><div><p className="eyebrow">STEP 1 OF 2</p><h2>Send money</h2></div><span className="secure-pill"><ShieldCheck size={14} /> Secure</span></div><form onSubmit={(event) => { event.preventDefault(); go('sendmoney-confirm-screen') }}><label>From<input data-agent-id="sendmoney-from-input" value="Everyday Checking •••• 4821" readOnly /></label><label>To<select data-agent-id="sendmoney-recipient-select" value={payee.id} onChange={(event) => setTransfer({ ...transfer, contactId: event.target.value })}>{payees.map((contact) => <option key={contact.id} value={contact.id}>{contact.name} {contact.account}</option>)}</select></label><label>Amount<div className="amount-input"><span>$</span><input data-agent-id="sendmoney-amount-input" value={transfer.amount} onChange={(event) => setTransfer({ ...transfer, amount: event.target.value })} type="number" min="0.01" step="0.01" required /></div></label><button data-agent-id="sendmoney-submit" className="primary-button" type="submit">Review transfer <ArrowUpRight size={17} /></button></form></section><section className="scheduled"><div className="section-heading"><div><p className="eyebrow">SHORTCUT</p><h2>Paying a bill instead?</h2></div><button data-agent-id="sendmoney-go-paybill" className="text-button" onClick={() => go('paybill-screen')}>Pay a bill <ChevronRight size={14} /></button></div></section></div>
}

function SendMoneyConfirmPage({ transfer, go }) {
  const payee = payees.find((contact) => contact.id === transfer.contactId) || payees[0]
  return <div className="transfer-page"><section className="transfer-form"><div className="section-heading"><div><p className="eyebrow">STEP 2 OF 2</p><h2>Review transfer</h2></div><span className="secure-pill"><ShieldCheck size={14} /> Secure</span></div><div className="review-list"><ReviewRow label="From" value="Everyday Checking •••• 4821" agentId="sendmoney-confirm-from" /><ReviewRow label="To" value={`${payee.name} ${payee.account}`} agentId="sendmoney-confirm-to" /><ReviewRow label="Amount" value={money(transfer.amount)} agentId="sendmoney-confirm-amount" /><ReviewRow label="Fee" value="$0.00" agentId="sendmoney-confirm-fee" /><ReviewRow label="Arrives" value="Instantly" agentId="sendmoney-confirm-arrival" /></div><div className="flow-actions"><button data-agent-id="sendmoney-confirm-back" className="secondary-button" onClick={() => go('sendmoney-screen')}><ArrowLeft size={16} /> Edit</button><button data-agent-id="sendmoney-confirm-approve" className="primary-button" onClick={() => go('sendmoney-success-screen')}>Confirm &amp; send <ArrowUpRight size={17} /></button></div></section></div>
}

function SendMoneySuccessPage({ transfer, go }) {
  const payee = payees.find((contact) => contact.id === transfer.contactId) || payees[0]
  return <div className="transfer-page"><section className="transfer-form"><div className="success-state"><span><Check size={25} /></span><h2>Transfer sent</h2><p>Your {money(transfer.amount)} transfer to {payee.name} is on its way.</p><div className="flow-actions"><button data-agent-id="sendmoney-success-another" className="secondary-button" onClick={() => go('sendmoney-screen')}>Send another</button><button data-agent-id="sendmoney-success-home" className="primary-button" onClick={() => go('home-screen')}><Home size={16} /> Back to home</button></div></div></section></div>
}

function PayBillPage({ bill, setBill, go }) {
  const selected = billers.find((entry) => entry.id === bill.billerId) || billers[0]
  return <div className="transfer-page"><section className="scheduled"><div className="section-heading"><div><p className="eyebrow">STEP 1 OF 2</p><h2>Choose a biller</h2></div><button data-agent-id="paybill-add-biller" className="round-control" aria-label="Add a biller"><Plus size={17} /></button></div>{billers.map((biller) => <button data-agent-id={`paybill-biller-${biller.id}`} key={biller.id} className={`scheduled-item biller-option ${selected.id === biller.id ? 'selected' : ''}`} onClick={() => setBill({ billerId: biller.id, amount: biller.amount })}><span className={`bill-icon ${biller.tone}`}>{biller.glyph}</span><div><strong>{biller.name}</strong><small>Due {biller.due} <span>•</span> {biller.category}</small></div><strong>{money(biller.amount)}</strong></button>)}</section><section className="transfer-form"><div className="section-heading"><div><p className="eyebrow">PAYMENT</p><h2>{selected.name}</h2></div><span className="secure-pill"><Receipt size={14} /> {selected.category}</span></div><form onSubmit={(event) => { event.preventDefault(); go('paybill-confirm-screen') }}><label>Pay from<input data-agent-id="paybill-from-input" value="Everyday Checking •••• 4821" readOnly /></label><label>Amount<div className="amount-input"><span>$</span><input data-agent-id="paybill-amount-input" value={bill.amount} onChange={(event) => setBill({ ...bill, amount: event.target.value })} type="number" min="0.01" step="0.01" required /></div></label><button data-agent-id="paybill-submit" className="primary-button" type="submit">Review payment <ArrowUpRight size={17} /></button></form></section></div>
}

function PayBillConfirmPage({ bill, go }) {
  const selected = billers.find((entry) => entry.id === bill.billerId) || billers[0]
  return <div className="transfer-page"><section className="transfer-form"><div className="section-heading"><div><p className="eyebrow">STEP 2 OF 2</p><h2>Review payment</h2></div><span className="secure-pill"><ShieldCheck size={14} /> Secure</span></div><div className="review-list"><ReviewRow label="Biller" value={selected.name} agentId="paybill-confirm-biller" /><ReviewRow label="Category" value={selected.category} agentId="paybill-confirm-category" /><ReviewRow label="Pay from" value="Everyday Checking •••• 4821" agentId="paybill-confirm-from" /><ReviewRow label="Amount" value={money(bill.amount)} agentId="paybill-confirm-amount" /><ReviewRow label="Due" value={selected.due} agentId="paybill-confirm-due" /></div><div className="flow-actions"><button data-agent-id="paybill-confirm-back" className="secondary-button" onClick={() => go('paybill-screen')}><ArrowLeft size={16} /> Edit</button><button data-agent-id="paybill-confirm-approve" className="primary-button" onClick={() => go('paybill-success-screen')}>Confirm &amp; pay <ArrowUpRight size={17} /></button></div></section></div>
}

function PayBillSuccessPage({ bill, go }) {
  const selected = billers.find((entry) => entry.id === bill.billerId) || billers[0]
  return <div className="transfer-page"><section className="transfer-form"><div className="success-state"><span><Check size={25} /></span><h2>Bill paid</h2><p>Your {money(bill.amount)} payment to {selected.name} is confirmed.</p><div className="flow-actions"><button data-agent-id="paybill-success-another" className="secondary-button" onClick={() => go('paybill-screen')}>Pay another bill</button><button data-agent-id="paybill-success-home" className="primary-button" onClick={() => go('home-screen')}><Home size={16} /> Back to home</button></div></div></section></div>
}

function ProfilePage({ logout }) { return <div className="profile-page"><div className="profile-hero"><span className="large-avatar">AS</span><div><h2>Alex Smith</h2><p className="muted">alex.smith@example.com</p></div></div><div className="settings-list"><button data-agent-id="profile-personal-details"><UserRound size={19} /> Personal details <ChevronRight size={16} /></button><button data-agent-id="profile-security"><ShieldCheck size={19} /> Security &amp; privacy <ChevronRight size={16} /></button><button data-agent-id="profile-notifications"><Bell size={19} /> Notifications <ChevronRight size={16} /></button><button data-agent-id="profile-logout" className="logout" onClick={logout}><ArrowUpRight size={19} /> Log out</button></div></div> }
function ChatModal({ messages, onClose, onSend }) { const [input, setInput] = useState(''); const submit = (text) => { onSend(text); setInput('') }; return <div className="chat-backdrop" onClick={onClose}><section className="chat-modal" onClick={(event) => event.stopPropagation()}><header><div><span className="assistant-icon"><Sparkles size={17} /></span><div><strong>Northstar assistant</strong><small>Always here to help</small></div></div><button data-agent-id="assistant-close" className="icon-button" onClick={onClose}><X size={19} /></button></header><div className="chat-body"><div className="assistant-message">Hi Alex, I’m your financial assistant. What can I help you with today?</div>{messages.map((message, index) => <div className={`chat-message ${message.from}`} key={`${message.text}-${index}`}>{message.text}</div>)}</div><div className="suggestions">{[['check-balance', 'Check my balance'], ['transfer-money', 'Transfer money'], ['monthly-spend', 'Show monthly spend']].map(([id, suggestion]) => <button data-agent-id={`assistant-suggestion-${id}`} key={id} onClick={() => submit(suggestion)}>{suggestion}</button>)}</div><form className="chat-input" onSubmit={(event) => { event.preventDefault(); if (input.trim()) submit(input.trim()) }}><input data-agent-id="assistant-input" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask anything about your money" /><button data-agent-id="assistant-send" aria-label="Send message"><Send size={17} /></button></form></section></div> }

export default App
